import pandas as pd
import itertools 

# Read in the SARS-CoV-2 mutation data.
SARS_mutation_data = pd.read_csv("../results/expected_vs_actual_mut_counts/expected_vs_actual_mut_counts.csv")

# Create a list of the unique clades in the data set.
CLADES = {clade for clade in SARS_mutation_data.clade.to_list()}

# Generate clade comparisons and save as strings. 
COMPARISONS = [f"{clade1}_{clade2}" for clade1, clade2  in itertools.combinations(CLADES, 2)]

# Compare both nucleotide mutations and amino acid mutations.
MUTATION_TYPE = ["nt","aa"]

rule all:
	input:
		expand("results/pvalues_{mutation_type}.csv", mutation_type=MUTATION_TYPE)
	
rule calculate_p_values:
	input:
		 "../results/expected_vs_actual_mut_counts/expected_vs_actual_mut_counts.csv"
	output:
		temp("results/pvalues{comparisons}_{mutation_type}.csv")
	params:
		subset="all",
		min_expected=0,
		pseudo=0.5
	script:
		"scripts/calculate_p_values.R"

rule combine_data:
	input:
		expand("results/pvalues{comparisons}_{mutation_type}.csv", comparisons=COMPARISONS, mutation_type=MUTATION_TYPE)
	output:
		protected("results/pvalues_{mutation_type}.csv")
	shell:
		"awk '(NR == 1) || (FNR > 1)' {input} > {output}"
